# Usa a imagem oficial do Go (Alpine é uma versão super leve)
FROM golang:alpine
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o main .

EXPOSE 8080

# Roda o executável compilado
CMD ["./main"]